### ISSUE TITLE
[POKEPAKU] (Timid) Mar. 18, 2017 {F} {S}.pk7

### ISSUE THREAD

**Issue by Tobyheiam** [ReignOfComputer/RoCs-PC#5]
according to http://www.serebii.net/events/dex/151.shtml ,  if this mew is the old sea map mew which can be shiny, the ot is supposed not to be an event ot. so it seems this mew ([POKEPAKU] (Timid) Mar. 18, 2017 {F} {S}.pk7) is fake.

**Comment by Tobyheiam** [comment]
if this mew is distributed at taiwan,2006, i guess it cant be shiny.

**Comment by stgiga** [comment]
Hello Toby. I, St. GIGA was the person who requested that THIS Mew be RNG'd by suloku, and to answer your question, yes, the Mew is the Old Sea Map Mew,  but intentionally RNG'd to be as close to the PokePakku mew as possible, while also being Shiny Flawless due to a quirk with the PID/ID/IV correlation. All data fields besides the secret ID are and can be the same as the PokePark Taiwan 2006 Mew. A little known fact about GBA events is that PokePakku Mew are able to have any nature. They also share the same caught level, fateful encounter flag, initial moveset, region, and are able to have the same Trainer Name, ID, and Gender as a Faraway island mew. Faraway Island mew do not have to be nicknamed, and the PID method that creates one allows for one Flawless PID that with the event ID from the Pokepark Taiwan Mew, and the Secret ID of 31337 (Obtainable via RNG manipulation using the SRed/RNG'd TID  at the start of the save file), creates a Shiny Flawless Mew, that with the correct OT name and Gender, creates this mew if it is either: not nicknamed like this one, or B: nicknamed on a save file with all the same origin data (Again, doable via RNG). If a player wants, they could very well name their girl trainer "Pokepakku" in katakana, and rng/sr the ID numbers, and wait the 34.25 days to press a to get this exact mew, and catch it in a normal Pokeball to match the event. 

FYI, Just because this set of circumstances is SO unique that THIS mew IS the only one which fulfills ALL of them, IT does NOT mean that THIS mew was obtained via ANY hacking OR cheating. Suloku spent several days of HIS time to RNG this on an Emulator with NO cheats, but with speedups, so please do NOT go out and accuse ME of faking THIS mew. The ONE and ONLY thing that distinguishes THIS heavily RNG'd Faraway Island mew from a normal Pokepakku Taiwan 2006 mew like the one you refer to in the second comment IS the secret ID, which, in order to make the PID shiny, has to be "31337" instead of "00000" That makes ALL the difference, and serves as a watermark to let people know that this is an RNG'd Faraway Island Mew, and NOT a PokePakku Taiwan 2006 Mew. It also disclaims that this is NOT an impossibly rare Shiny pokepakku Mew, and just a VERY specific Faraway Island Mew, but DISGUISED as a Pokepakku Taiwan 2006 Mew, instead of the actual 2006 Pokepakku Mew. A player can use ANY OT name for their pokemon, even event ones, so I hate to break it to you, but I did not hack the Mew. It even has Legitimate Japanese Emerald Trashbytes in the 3gpkm version of the Mew.

Without RNG under VERY unique conditions, this Mew is near-impossible to own. Any copies of this Mew are automatically clones, as there is only ONE possible version of this that meets the criteria of BOTH events, and THIS is IT!

Sorry for the rant, but the Mew IS 100% Legit. Please DON'T bother ME or ANYONE else about THIS Mew, UNLESS you have a FULLY LEGITIMATE complaint about IT!

Again, to clarify, the Faraway Island Mew CAN have ANY OT and ID combo! Therefore, this is LEGIT. Go check Bulbapedia, and Serebii with your readers and thinking caps on before you try and doubt THIS mew's legitimacy, however rare and unique it MAY be!

**Comment by ReignOfComputer** [comment]
As said on ProjectPokemon, @Tobyheiam has a legit reason for thinking it's hacked, given the coinciding TID and OT. Just explain nicely next time.
